name: funichar_clon_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  upi_india: ^3.0.1
  easy_search_bar: ^2.3.1
  flutter_icons: ^1.1.0
  flutter_image_slideshow: ^0.1.4
 
  
 
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

      - assets/sofa set image/61vWTGxwgAL._SL1100_.jpg
      - assets/sofa set image/81f2TBWBXWL._SL1366_.jpg
      - assets/sofa set image/Designer-Sofa-Set-in-Sky-Blue-And-White_4.jpg
      - assets/sofa set image/download.jpg
      - assets/sofa set image/Hb123ed728de64257b9579fc443d9bf11q.jpg
      - assets/sofa set image/HTB1agcpeG5s3KVjSZFNq6AD3FXav.jpg
      - assets/sofa set image/Jacoix-311-Sofa-Set.jpg
      - assets/sofa set image/living-room-sofa-set-500x500.webp
      - assets/sofa set image/wooden-sofa-set.jpg
      - assets/sofa set image/wooden-sofa-set.jpg
      - assets/sofa set image/sofas.jpg

      - assets/dining room pling/tables.jpg
      - assets/dining room pling/banch.jpg
      - assets/dining room pling/photo.jpg
      - assets/dining room pling/michael-glass-unsplash-1366x768.webp
      - assets/dining room pling/design.jpg
      - assets/dining room pling/Cover-PNG-01-1.webp
      - assets/dining room pling/Designe.jpg
      - assets/dining room pling/dining tabal.jpg
      - assets/dining room pling/dining.webp
      - assets/dining room pling/dining-room.png
      
      - assets/pepperfry-diwali-sale.jpg
      - assets/bed.jpg
      - assets/bads.room/depositphoto.webp
      - assets/bads.room/beds.jpg
      - assets/bads.room/istockphoto-.jpg
      - assets/bads.room/istockphoto.jpg
      - assets/bads.room/bedroom-.jpg
      - assets/bads.room/Black-Wooden-Bed.jpg.webp
      - assets/bads.room/bedss.jpg
      - assets/bads.room/maxresdefault.jpg
      - assets/bads.room/besddu.jpg
      - assets/bads.room/Scott_Storage_Bed_King_Finish_Californian_Walnut_LP.jpg
      - assets/bads.room/bookcase-bed.jpg

      - assets/Sofa-set-designs.jpg
      - assets/Living_room_idea_wood_details.jpg
      - assets/add.png
      - assets/lining_room.jpg
      - assets/istockphoto-1177844431-170667a.jpg
      - assets/bad_room.jpg
      - assets/table.jpg
      - assets/rosewood-sheesham.webp
      - assets/mirror.jpg
      - assets/security-alarm-bad.png
      - assets/Shivam_Lites.jpg
      - assets/alamari_Door.jpg
      - assets/gaming_chair.jpg
      - assets/other-image/gaming_chair _new.jpg
      - assets/double_bedsheet.jpg
      - assets/swings.jpg
      - assets/seater-sofa.webp
      - assets/other-image/bed mattress.png
      - assets/other-image/smart chandelier.webp
      - assets/kids_study_table.jpg
      - assets/lamps.webp
      - assets/bed.jpg
      - assets/lamp.jpg
      - assets/81sWQ7IaGaL._AC_SX679_.jpg
      - assets/natire.jpg
      - assets/towel-for-gym-cotton.webp
      - assets/vases.jpg
      - assets/drinkware.webp
      - assets/MARBLE-COLLECTION.jpg
      - assets/Coffee_Table.jpg
      - assets/other-image/TV Consol.png
      - assets/grey-wool.jpg
      - assets/baby-jhula-.jpg
      - assets/other-image/ceramic bolw.webp
      - assets/phone-pe.png
      - assets/google-pay-india.png
      - assets/bhim.png
      - assets/paypal.png
      - assets/paytm.png
      - assets/Bed-headboard-.jpg
      - assets/other-image/nest.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
